server:
  port: 8085
spring.jpa:
  properties:
    hibernate.enable_lazy_load_no_trans: true
  database: POSTGRESQL
  hibernate.ddl-auto: create
  show-sql: true
spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/demo_spring
  username: postgres
  password: 1111111111
spring:
  sql:
    init:
      platform: postgres
      mode: never
  main:
    allow-circular-references: true